version: '3.1'
services:
    web:
        build: .
        volumes:
            - ./:/app
        ports:
            - '3006:80'
        links:
            - postgres
    postgres:
        image: postgres # specify image to build container from
        ports:
            - '5430:5432'
        environment:
            - POSTGRES_PASSWORD:mysecretpassword123
